name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        jdk: [ 11, 8, 17 ]
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Pull Request Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
        if: github.head_ref != ''
      - name: Push Checkout
        uses: actions/checkout@v2
        if: github.head_ref == ''
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.jdk}}
          distribution: 'temurin'
      - name: Build
        id: build
        run: ./.ci-build-without-test.sh

      - name: PICO Typecheck Test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
             ./.ci-prepare.sh
             ./gradlew ImmutabilityTypecheckTest

      - name: PICO Typecheck AllSystems Test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          ./.ci-prepare.sh
          ./gradlew ImmutabilityTypecheckBaseAllSystemsTest

      - name: PICO Typecheck Extended Test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          ./.ci-prepare.sh
          ./gradlew ImmutabilityTypecheckExtendedTest

      - name: PICO Glacier TypeCheck Test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          ./.ci-prepare.sh
          ./gradlew ImmutabilityTypecheckGlacierTest

      - name: PICO Inference Initial Typecheck Test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          ./.ci-prepare.sh
          ./gradlew ImmutabilityInferenceInitialTypecheckTest

      - name: PICO Inference Test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          ./.ci-prepare.sh
          ./gradlew ImmutabilityInferenceTest

      - name: PICO ReIm Inference Test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          ./.ci-prepare.sh
          ./gradlew ImmutabilityReImInferenceTest
